@startuml
start
:Попытка считать переданные
        числа из полей ввода;
if (Числа корректные) then (true)
    if (((a <= x && b <= y) ||
    (a <= y && b <= x) ||
    (a <= x && c <= y) ||
    (a <= y && c <= x) ||
    (b <= x && c <= y) ||
    (b <= y && c <= x))) then (true)
    :"Кирпич пройдет через отверстие.";
    else (false)
      :"Кирпич не пройдет через отверстие.";
    endif
else (false)
  :"Ошибка: Введите корректные числа";
  stop
endif
stop
@enduml
